### ISSUE TITLE
GIT CMS: Alpha release checklist

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-content#12]
Things to do:

- [ ] Migrate to provider model for git instead of dedicated class
- [ ] Introduce "Environment" setting
- [ ] Migrate UI Designer to use standard content API instead of Git Content API
- [ ] Remove specific Git Web API
- [ ] Remove hard coded config settings 
- [ ] Modify default theme to enable GUI designer
- [ ] Switch GUI designer to token based authentication instead of hard coded keys

**Overview**
The basic concept of branches in CMS is the environment the customer work in. It allows to isolate changes to pages inside specific environment.

There will always be default branch (called "master") that production environment typically runs off. Branches are not meant to be long term and should be deleted once content is prepared. When new branch is created, it is created based on content currently stored in "master" branch.

**Implement**
Admin GUI needs to be extended to allow picking a branch, the easiest approach will be adding dropdown next to the search in pages view. Once branch is changed, user is working on the selected environment. The selection should be persisted.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
