### ISSUE TITLE
Design Page Editor (json)

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-content#13]
- [ ] Designer should be an angular js based html application (doesn't need to be .net web app)
- [ ] Refactor API used to save content to use standard storage API's available in the platform instead of new GIT API
- [ ] Cleanup existing Designer project (remove unused files, restore correct design templates/css, restore edit settings_data.json functionality from the first prototype)
- [ ] Fix authentication, we should not hard code keys inside javascript
- [ ] Make designer work with our the default electronics theme

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
